version: '3'

services:
  db:
    image: postgres:14.2
    restart: always
    ports:
      - "${PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: products-db
    volumes:
      - ./postgres:/var/lib/postgresql/data